# Generated by Django 4.2.9 on 2026-04-17 01:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VAPBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_type', models.CharField(choices=[('ghee', 'Ghee'), ('paneer', 'Paneer'), ('curd', 'Curd / Yogurt'), ('butter', 'Butter'), ('buttermilk', 'Buttermilk'), ('khoya', 'Khoya')], max_length=30)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('produced', 'Produced'), ('packaged', 'Packaged'), ('dispatched', 'Dispatched'), ('sold', 'Sold')], default='produced', max_length=20)),
                ('total_milk_used_litres', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_batches', to='farmers.farmer')),
                ('source_farmers', models.ManyToManyField(blank=True, related_name='vap_batches', to='farmers.farmer')),
            ],
            options={
                'ordering': ['-production_date'],
            },
        ),
        migrations.CreateModel(
            name='MilkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10)),
                ('quantity_litres', models.DecimalField(decimal_places=1, max_digits=6)),
                ('fat_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('snf_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_logs', to='farmers.farmer')),
            ],
            options={
                'ordering': ['-date', '-session'],
                'unique_together': {('farmer', 'date', 'session')},
            },
        ),
    ]
