# Generated by Django 4.2.9 on 2026-04-17 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(default='stress', max_length=20)),
                ('severity', models.CharField(default='medium', max_length=10)),
                ('message_en', models.TextField()),
                ('message_ta', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='farmers.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NDVIReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('ndvi_value', models.DecimalField(decimal_places=3, max_digits=5)),
                ('health_status', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('moderate', 'Moderate'), ('stressed', 'Stressed'), ('critical', 'Critical')], max_length=20)),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndvi_readings', to='farmers.farm')),
            ],
            options={
                'ordering': ['-reading_date'],
                'unique_together': {('farm', 'reading_date')},
            },
        ),
    ]
