# Generated by Django 4.2.9 on 2026-04-17 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(default='Madurai', max_length=100)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('manager', 'Cooperative Manager'), ('nabard', 'NABARD Officer')], default='farmer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_acres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('crop_type', models.CharField(choices=[('sorghum', 'Sorghum / Cholam'), ('maize', 'Maize / Makka Cholam'), ('napier', 'Napier Grass'), ('paddy', 'Paddy / Rice'), ('sugarcane', 'Sugarcane'), ('cotton', 'Cotton'), ('groundnut', 'Groundnut'), ('other', 'Other')], default='sorghum', max_length=50)),
                ('sowing_date', models.DateField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farmers.farmer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=50)),
                ('breed', models.CharField(choices=[('hf', 'Holstein Friesian'), ('jersey', 'Jersey'), ('kangayam', 'Kangayam'), ('crossbred', 'Crossbred'), ('murrah', 'Murrah Buffalo'), ('other', 'Other')], max_length=50)),
                ('age_years', models.PositiveIntegerField(default=2)),
                ('is_milking', models.BooleanField(default=True)),
                ('expected_daily_yield_litres', models.DecimalField(decimal_places=1, default=10.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cattle', to='farmers.farmer')),
            ],
        ),
    ]
